#!/usr/bin/env bash

export source_directory="${BASH_SOURCE[0]%misspell-fixer}"
if [[ "$source_directory" == "" ]]
then
    source_directory='./'
fi
if [ ! -f "${source_directory}/rules/safe.0.sed" ]
then
    source_directory="/usr/share/misspell-fixer/"
fi

export rules_directory="${rule_file_base}rules"

source "${source_directory}/lib/initialisation_functions.sh"
source "${source_directory}/lib/main_functions.sh"

init_variables

parse_basic_options "$@"
retval=$?

if [[ $retval == 0 ]]
then
    process_parameter_rules
    retval=$?
fi

if [[ $retval == 0 ]]
then
    if [[ $opt_debug = 1 ]]
    then
        set -x
    fi
    check_grep_version
    check_sed_arguments
    preprocess_rules
    main_work prepare_prefilter_input_from_find 0 '' /dev/null
    retval=$?
    rm $tmpfile.prep.grep.rules $tmpfile.prep.grep.rules.w $tmpfile.prep.allsedrules
    if [[ $opt_debug = 1 ]]
    then
        set +x
    fi
fi

if [[ "$SHUNIT_VERSION" = "" ]]
then
    exit $retval
else
    return $retval
fi
