version: 2
jobs:
    build-and-test:
        docker:
            - image: circleci/buildpack-deps:stretch-curl
        steps:
            - checkout
            - run:
                name: Prepare environment
                command: make prepare_environment
            - run:
                name: Run tests
                command: make test
