version: 2
jobs:
    build:
        docker:
            - image: circleci/buildpack-deps:stretch-curl
        steps:
            - checkout
            - run: sudo apt-get install make cmake g++ zlib1g-dev
            - run:
                name: Prepare environment
                command: make prepare_environment
            - run:
                name: Run tests
                command: make test
